---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xaowpmi8h0df/public_html
    - /bin/mkdir -p $DEPLOYPATH/cms $DEPLOYPATH/api
    - /bin/cp index.html 404.html .htaccess $DEPLOYPATH/
    - /bin/cp cms/index.html $DEPLOYPATH/cms/
    - /bin/cp api/fetch.php api/feeds.php api/data.php api/.htaccess api/mcp-*.php api/rewrite.php api/images.php api/videos.php api/hit.php api/status.php api/auth.php api/session.php api/credit.php $DEPLOYPATH/api/
