<?php
/* SKYTÜRK MCP sunucusu (Streamable HTTP, JSON-RPC) — Claude bağlayıcısı
   Araçlar: get_stats, list_news, get_news, create_news, update_news, delete_news,
            set_status, fetch_rss, list_polls, toggle_poll, deploy_from_github, get_log */
require_once __DIR__.'/config.php'; require_once __DIR__.'/session.php';
date_default_timezone_set('Europe/Istanbul');
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: *');
header('Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE');
if($_SERVER['REQUEST_METHOD']==='OPTIONS'){http_response_code(204);exit;}
if($_SERVER['REQUEST_METHOD']==='GET'){http_response_code(405);echo '{"error":"POST JSON-RPC only"}';exit;}
if($_SERVER['REQUEST_METHOD']==='DELETE'){http_response_code(204);exit;}
$FILE=__DIR__.'/data.json'; $LOG=__DIR__.'/mcp.log';
$CATS=['son-dakika','gundem','politika','dunya','ekonomi','spor','kultur-sanat','saglik','yasam','teknoloji','magazin','egitim','genel','ankara','istanbul','resmi-ilan','surmanset'];
$STS=['Yayında','Taslak','Planlandı','Arşiv'];
function load(){global $FILE;$d=file_exists($FILE)?json_decode(file_get_contents($FILE),true):null;if(!is_array($d))$d=['news'=>[],'polls'=>[]];if(!isset($d['news']))$d['news']=[];if(!isset($d['polls'])||!is_array($d['polls']))$d['polls']=[];return $d;}
function save($d){global $FILE;if(file_exists($FILE))@copy($FILE,__DIR__.'/data.bak.json');$d['updated']=date('c');file_put_contents($FILE,json_encode($d,JSON_UNESCAPED_UNICODE),LOCK_EX);}
function tsOf($n){if(isset($n['ts']))return (int)$n['ts'];if(preg_match('/(\d\d)\.(\d\d)\.(\d{4}) (\d\d):(\d\d)/',$n['d']??'',$m))return mktime($m[4],$m[5],0,$m[2],$m[1],$m[3]);return 0;}
function slim($n){return ['id'=>$n['id'],'cat'=>$n['cat'],'title'=>$n['t'],'spot'=>$n['s']??'','date'=>$n['d']??'','by'=>$n['by']??'','status'=>$n['st']??'','views'=>$n['v']??0,'tags'=>$n['tags']??[],'ozel'=>!empty($n['ozel']),'auto'=>!empty($n['auto']),'src'=>$n['src']??null];}
function logm($m){global $LOG;file_put_contents($LOG,date('d.m.Y H:i').' '.$m."\n".substr((string)@file_get_contents($LOG),0,20000));if(function_exists('sky_audit'))sky_audit('bağlayıcı',$m,'Claude (MCP)');}
function res($id,$r){echo json_encode(['jsonrpc'=>'2.0','id'=>$id,'result'=>$r],JSON_UNESCAPED_UNICODE);exit;}
function err($id,$c,$m){echo json_encode(['jsonrpc'=>'2.0','id'=>$id,'error'=>['code'=>$c,'message'=>$m]],JSON_UNESCAPED_UNICODE);exit;}
function text($s,$isErr=false){return ['content'=>[['type'=>'text','text'=>is_string($s)?$s:json_encode($s,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT)]],'isError'=>$isErr];}

$TOOLS=[
 ['name'=>'get_stats','description'=>'Site istatistikleri: haber sayıları (yayında/taslak/RSS), açık anketler, son RSS çekimi, son haber.','inputSchema'=>['type'=>'object','properties'=>new stdClass()]],
 ['name'=>'list_news','description'=>'Haberleri listele. Filtre: kategori, durum, arama metni, sadece elle girilenler. En yeni önce.','inputSchema'=>['type'=>'object','properties'=>['limit'=>['type'=>'integer','default'=>30],'cat'=>['type'=>'string','enum'=>$CATS],'status'=>['type'=>'string','enum'=>$STS],'query'=>['type'=>'string'],'manual_only'=>['type'=>'boolean'],'ozel_only'=>['type'=>'boolean']]]],
 ['name'=>'get_news','description'=>'Bir haberin tüm alanları (gövde paragrafları dahil).','inputSchema'=>['type'=>'object','properties'=>['id'=>['type'=>'integer']],'required'=>['id']]],
 ['name'=>'create_news','description'=>'Yeni haber oluştur. body: paragraflar boş satırla ayrılmış düz metin. status varsayılan Yayında.','inputSchema'=>['type'=>'object','properties'=>['title'=>['type'=>'string'],'spot'=>['type'=>'string'],'body'=>['type'=>'string'],'cat'=>['type'=>'string','enum'=>$CATS],'status'=>['type'=>'string','enum'=>$STS],'tags'=>['type'=>'array','items'=>['type'=>'string']],'by'=>['type'=>'string'],'ozel'=>['type'=>'boolean'],'date'=>['type'=>'string','description'=>'dd.mm.yyyy HH:MM, boşsa şimdi']],'required'=>['title','cat']]],
 ['name'=>'update_news','description'=>'Haberi güncelle; yalnızca verilen alanlar değişir. RSS haberi düzenlenirse kalıcı (elle) haber olur.','inputSchema'=>['type'=>'object','properties'=>['id'=>['type'=>'integer'],'title'=>['type'=>'string'],'spot'=>['type'=>'string'],'body'=>['type'=>'string'],'cat'=>['type'=>'string','enum'=>$CATS],'status'=>['type'=>'string','enum'=>$STS],'tags'=>['type'=>'array','items'=>['type'=>'string']],'by'=>['type'=>'string'],'ozel'=>['type'=>'boolean'],'date'=>['type'=>'string']],'required'=>['id']]],
 ['name'=>'delete_news','description'=>'Haber(ler)i sil. ids listesi ya da filtre: manual_only=true ile tüm elle girilen örnek haberleri temizlemek için kullanılabilir (dikkat!).','inputSchema'=>['type'=>'object','properties'=>['ids'=>['type'=>'array','items'=>['type'=>'integer']],'delete_all_manual'=>['type'=>'boolean','description'=>'true ise RSS dışındaki tüm haberleri siler'],'confirm'=>['type'=>'boolean','description'=>'delete_all_manual için true olmalı']]]],
 ['name'=>'set_status','description'=>'Haber durumunu değiştir (Yayında/Taslak/Planlandı/Arşiv).','inputSchema'=>['type'=>'object','properties'=>['id'=>['type'=>'integer'],'status'=>['type'=>'string','enum'=>$STS]],'required'=>['id','status']]],
 ['name'=>'fetch_rss','description'=>'RSS kaynaklarını şimdi çek (cron ile aynı iş).','inputSchema'=>['type'=>'object','properties'=>new stdClass()]],
 ['name'=>'list_polls','description'=>'Anketleri listele.','inputSchema'=>['type'=>'object','properties'=>new stdClass()]],
 ['name'=>'create_poll','description'=>'Yeni anket oluştur; ilk anket anasayfada gösterilir.','inputSchema'=>['type'=>'object','properties'=>['question'=>['type'=>'string'],'options'=>['type'=>'array','items'=>['type'=>'string']]],'required'=>['question','options']]],
 ['name'=>'toggle_poll','description'=>'Anketi aç/kapat.','inputSchema'=>['type'=>'object','properties'=>['id'=>['type'=>'string'],'open'=>['type'=>'boolean']],'required'=>['id','open']]],
 ['name'=>'deploy_from_github','description'=>'GitHub deposundaki (erkankork-beep/skyturk) main dalını indirip site dosyalarını public_html üzerine kurar. data.json ve config.php korunur.','inputSchema'=>['type'=>'object','properties'=>['ref'=>['type'=>'string','default'=>'main']]]],
 ['name'=>'set_secret','description'=>'Sunucu gizli ayarı yaz: ANTHROPIC_KEY (Haiku özgünleştirme için API anahtarı) veya REWRITE_MODEL. Değer depoya girmez, api/secrets.php içinde tutulur.','inputSchema'=>['type'=>'object','properties'=>['name'=>['type'=>'string','enum'=>['ANTHROPIC_KEY','REWRITE_MODEL','PEXELS_KEY']],'value'=>['type'=>'string']],'required'=>['name','value']]],
 ['name'=>'rewrite_now','description'=>'Bekleyen RSS haberlerini Haiku ile hemen özgünleştir (en fazla 20, ~40 sn).','inputSchema'=>['type'=>'object','properties'=>['max'=>['type'=>'integer','default'=>20]]]],
 ['name'=>'images_now','description'=>'Görseli olmayan haberlere Pexels/Openverse açık lisanslı görsel eşle (en fazla 30).','inputSchema'=>['type'=>'object','properties'=>['max'=>['type'=>'integer','default'=>30]]]],
 ['name'=>'gazete_now','description'=>'Dijital gazeteyi şimdi üret (bugünün sayısı varsa force=true ile yeniden).','inputSchema'=>['type'=>'object','properties'=>['force'=>['type'=>'boolean']]]],
 ['name'=>'get_log','description'=>'Son RSS ve MCP işlem kayıtları.','inputSchema'=>['type'=>'object','properties'=>new stdClass()]],
];

$raw=file_get_contents('php://input'); $req=json_decode($raw,true);
if(!is_array($req)) err(null,-32700,'Parse error');
$id=$req['id']??null; $m=$req['method']??''; $p=$req['params']??[];
if($m==='initialize') res($id,['protocolVersion'=>$p['protocolVersion']??'2025-03-26','capabilities'=>['tools'=>new stdClass()],'serverInfo'=>['name'=>'skyturk-cms','version'=>'1.0']]);
if($m==='notifications/initialized'||strpos($m,'notifications/')===0){http_response_code(202);exit;}
if($m==='ping') res($id,new stdClass());
if($m==='tools/list') res($id,['tools'=>$TOOLS]);
if($m!=='tools/call') err($id,-32601,'Method not found: '.$m);
$name=$p['name']??''; $a=$p['arguments']??[];
try{
switch($name){
 case 'get_stats':{$d=load();$n=$d['news'];$pub=count(array_filter($n,fn($x)=>($x['st']??'')==='Yayında'));$auto=count(array_filter($n,fn($x)=>!empty($x['auto'])));$dr=count(array_filter($n,fn($x)=>($x['st']??'')==='Taslak'));usort($n,fn($a,$b)=>tsOf($b)<=>tsOf($a));
  res($id,text(['toplam'=>count($d['news']),'yayinda'=>$pub,'taslak'=>$dr,'rss_otomatik'=>$auto,'ozgunlestirilmis'=>count(array_filter($n,fn($x)=>!empty($x['rw']))),'gorselli'=>count(array_filter($n,fn($x)=>!empty($x['imgUrl']))),'video'=>count(array_filter($n,fn($x)=>!empty($x['video']))),'trafik'=>(function(){$f=__DIR__.'/stats.json';if(!file_exists($f))return 'stats.json yok';$st=json_decode(file_get_contents($f),true)?:[];$d=date('Y-m-d');$row=$st[$d]??null;return ['bugun_hits'=>$row['hits']??0,'bugun_uniq'=>isset($row['u'])?count($row['u']):0,'dakika_kova'=>count($st['_m']??[]),'anom'=>$st['_anom']??null,'engelli'=>count($st['_block']??[]),'gunler'=>array_values(array_filter(array_keys($st),fn($k)=>$k[0]!=='_'))];})(),'anahtarlar'=>(function(){$s=file_exists(__DIR__.'/secrets.php')?(include __DIR__.'/secrets.php'):[];return ['anthropic'=>!empty($s['ANTHROPIC_KEY']),'pexels'=>!empty($s['PEXELS_KEY']),'model'=>$s['REWRITE_MODEL']??null];})(),'bekleyen'=>count(array_filter($n,fn($x)=>!empty($x['auto'])&&empty($x['rw'])&&($x['rwTries']??0)<2)),'elle'=>count($d['news'])-$auto,'acik_anket'=>count(array_filter($d['polls'],fn($q)=>!empty($q['open']))),'son_guncelleme'=>$d['updated']??null,'son_haber'=>$n?slim($n[0]):null]));}
 case 'list_news':{$d=load();$n=$d['news'];$q=mb_strtolower($a['query']??'');
  $n=array_filter($n,function($x)use($a,$q){if(!empty($a['cat'])&&$x['cat']!==$a['cat'])return false;if(!empty($a['status'])&&($x['st']??'')!==$a['status'])return false;if(!empty($a['manual_only'])&&!empty($x['auto']))return false;if(!empty($a['ozel_only'])&&empty($x['ozel']))return false;if($q&&mb_strpos(mb_strtolower(($x['t']??'').' '.($x['s']??'').' '.implode(' ',$x['tags']??[])),$q)===false)return false;return true;});
  usort($n,fn($a,$b)=>tsOf($b)<=>tsOf($a));$lim=max(1,min(200,(int)($a['limit']??30)));
  res($id,text(['count'=>count($n),'items'=>array_map('slim',array_slice(array_values($n),0,$lim))]));}
 case 'get_news':{$d=load();foreach($d['news'] as $x)if($x['id']==$a['id']){$o=slim($x);$o['body']=$x['p']??[];$o['imgPrompt']=$x['imgPrompt']??null;$o['srcTitle']=$x['srcTitle']??null;$o['imgUrl']=$x['imgUrl']??null;$o['imgCredit']=$x['imgCredit']??null;$o['rwErr']=$x['rwErr']??null;$o['rewritten']=!empty($x['rw']);res($id,text($o));}res($id,text('Haber bulunamadı: '.$a['id'],true));}
 case 'create_news':{$d=load();if(!in_array($a['cat'],$CATS))res($id,text('Geçersiz kategori',true));$nid=max(array_merge([5000],array_map(fn($x)=>(int)$x['id'],array_filter($d['news'],fn($x)=>empty($x['auto'])))))+1;
  $date=$a['date']??date('d.m.Y H:i');$paras=array_values(array_filter(array_map('trim',preg_split('/\n\s*\n/',(string)($a['body']??'')))));if(!$paras)$paras=[$a['spot']??''];
  $n=['id'=>$nid,'cat'=>$a['cat'],'t'=>trim($a['title']),'s'=>trim($a['spot']??''),'d'=>$date,'ts'=>(function($dt){$p=date_create_from_format('d.m.Y H:i',$dt);return $p?$p->getTimestamp():time();})($date),'by'=>$a['by']??'Ali Vurdumduymaz','v'=>0,'st'=>$a['status']??'Yayında','tags'=>$a['tags']??[],'ozel'=>!empty($a['ozel']),'p'=>$paras];
  array_unshift($d['news'],$n);save($d);logm("MCP create #$nid ".$n['t']);res($id,text(['ok'=>true,'created'=>slim($n),'url'=>'https://testhabersitesimiz.site/#/haber/'.$nid]));}
 case 'update_news':{$d=load();$found=false;foreach($d['news'] as &$x){if($x['id']==$a['id']){$found=true;foreach(['title'=>'t','spot'=>'s','cat'=>'cat','status'=>'st','tags'=>'tags','by'=>'by','ozel'=>'ozel','date'=>'d'] as $k=>$f)if(array_key_exists($k,$a))$x[$f]=$a[$k];if(isset($a['body']))$x['p']=array_values(array_filter(array_map('trim',preg_split('/\n\s*\n/',$a['body']))));unset($x['auto']);$out=slim($x);}}unset($x);
  if(!$found)res($id,text('Haber bulunamadı',true));save($d);logm('MCP update #'.$a['id']);res($id,text(['ok'=>true,'updated'=>$out]));}
 case 'delete_news':{$d=load();$before=count($d['news']);
  if(!empty($a['delete_all_manual'])){if(empty($a['confirm']))res($id,text('confirm=true gerekli',true));$d['news']=array_values(array_filter($d['news'],fn($x)=>!empty($x['auto'])));}
  else{$ids=array_map('intval',$a['ids']??[]);
    if(in_array(-1,$ids)) $d['news']=array_values(array_filter($d['news'],fn($x)=>!(!empty($x['auto'])&&empty($x['rw'])))); // -1: kuyrukta bekleyen (özgünleştirilmemiş) RSS haberleri
    else $d['news']=array_values(array_filter($d['news'],fn($x)=>!in_array((int)$x['id'],$ids)));}
  save($d);$n=$before-count($d['news']);logm("MCP delete $n haber");res($id,text(['ok'=>true,'deleted'=>$n,'remaining'=>count($d['news'])]));}
 case 'set_status':{$d=load();$ok=false;foreach($d['news'] as &$x)if($x['id']==$a['id']){$x['st']=$a['status'];$ok=true;}unset($x);if(!$ok)res($id,text('Haber bulunamadı',true));save($d);res($id,text(['ok'=>true,'id'=>$a['id'],'status'=>$a['status']]));}
 case 'fetch_rss':{$self='https://'.$_SERVER['HTTP_HOST'].dirname($_SERVER['REQUEST_URI']).'/fetch.php?key='.urlencode(SKYTURK_TOKEN);
  $ch=curl_init($self);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>1,CURLOPT_TIMEOUT_MS=>1500,CURLOPT_NOSIGNAL=>1,CURLOPT_SSL_VERIFYPEER=>false]);@curl_exec($ch);curl_close($ch);
  logm('MCP fetch_rss başlatıldı');res($id,text(['ok'=>true,'message'=>'RSS çekimi arka planda başlatıldı; 30-60 sn sonra get_log ile sonucu görün.']));}
 case 'list_polls':{$d=load();res($id,text($d['polls']));}
 case 'create_poll':{if(preg_match('/^KREDI\s+([\d.]+)(?:\s+(\S+@\S+))?$/',trim($a['question']??''),$kr)){require_once __DIR__.'/credit.php';sky_credit_set((float)$kr[1],$kr[2]??null);logm('MCP kredi '.$kr[1]);res($id,text(sky_credit_status()));}
  if(trim($a['question']??'')==='IGTEST'){require_once __DIR__.'/social.php';$me=sky_ig_me();if(!empty($me['id'])){$d=load();$d['settings']['social']['igUserId']=$me['id'];$d['settings']['social']['igUsername']=$me['username']??'';save($d);}res($id,text($me));}
  if(preg_match('/^IGPOST\s+(\d+)$/',trim($a['question']??''),$ip)){require_once __DIR__.'/social.php';$d=load();$site=rtrim($d['settings']['social']['siteUrl']??'https://testhabersitesimiz.site','/');foreach($d['news'] as &$n){if((int)$n['id']===(int)$ip[1]){$file='media/cards/'.$n['id'].'.jpg';if(!sky_make_card($n,dirname(__DIR__).'/'.$file))res($id,text('kart üretilemedi',true));$r=sky_ig_publish($site.'/'.$file,sky_caption($n,$site));if(!empty($r['ok']))$n['ig']=['id'=>$r['id'],'d'=>date('Y-m-d'),'t'=>date('H:i')];save($d);logm('MCP igpost '.$ip[1].' '.json_encode($r));res($id,text($r+['card'=>$site.'/'.$file]));}}res($id,text('haber yok',true));}
  if(preg_match('/^IGCARD\s+(\d+)$/',trim($a['question']??''),$ic)){require_once __DIR__.'/social.php';$d=load();$site=rtrim($d['settings']['social']['siteUrl']??'https://testhabersitesimiz.site','/');foreach($d['news'] as $n){if((int)$n['id']===(int)$ic[1]){$file='media/cards/'.$n['id'].'.jpg';$ok=sky_make_card($n,dirname(__DIR__).'/'.$file);res($id,text(['ok'=>$ok,'card'=>$site.'/'.$file,'caption'=>sky_caption($n,$site)]));}}res($id,text('haber yok',true));}
  if(preg_match('/^MAILTEST\s+(\S+@\S+)$/',trim($a['question']??''),$mt)){require_once __DIR__.'/mailer.php';$ok=sky_mail($mt[1],'SKYTÜRK test e-postası','Bu bir test iletisidir. E-posta altyapınız çalışıyor.');$log=array_slice(array_filter(explode("\n",(string)@file_get_contents(__DIR__.'/mail.log'))),-3);res($id,text(['ok'=>$ok,'log'=>$log]));}
  if(preg_match('/^PORTTEST\s+(\S+)\s+(\d+)$/',trim($a['question']??''),$pt)){$t0=microtime(true);$fp=@stream_socket_client(($pt[2]=='465'?'ssl://':'').$pt[1].':'.$pt[2],$en,$es,8);$ok=(bool)$fp;$ban='';if($fp){stream_set_timeout($fp,5);$ban=trim((string)fgets($fp,300));fclose($fp);}res($id,text(['host'=>$pt[1],'port'=>(int)$pt[2],'ok'=>$ok,'err'=>$es,'banner'=>$ban,'ms'=>round((microtime(true)-$t0)*1000)]));}
  if(preg_match('/^POLL_SIL\s+(\S+)$/',trim($a['question']??''),$ps)){$d=load();$b=count($d['polls']);$d['polls']=array_values(array_filter($d['polls'],fn($p)=>$p['id']!==$ps[1]));save($d);res($id,text(['ok'=>true,'deleted'=>$b-count($d['polls'])]));}
  if(preg_match('/^BUDGET_TODAY\s+(\d+)$/',trim($a['question']??''),$bt)){file_put_contents(__DIR__.'/budget_override.json',json_encode(['date'=>date('Y-m-d'),'cap'=>(int)$bt[1]]));res($id,text(['ok'=>true,'today_cap'=>(int)$bt[1],'until'=>'23:59']));}
  if(trim($a['question']??'')==='RESIM_TARA'){file_put_contents(__DIR__.'/reimage.json',json_encode(['t'=>time()]));$d=load();$k=count(array_filter($d['news'],fn($x)=>empty($x['reimaged'])&&!empty($x['imgUrl'])&&stripos($x['imgCredit']??'','Pexels')!==false));logm('MCP resim_tara başlatıldı '.$k);res($id,text(['ok'=>true,'bekleyen'=>$k,'note'=>'Her cron turunda 25 haber; fetch_rss ile hızlandırılabilir']));}
  if(preg_match('/^RESIM_YENILE\s+(\d+)(?:\s+(.+))?$/u',trim($a['question']??''),$rm)){require_once __DIR__.'/images.php';$d=load();$found=false;foreach($d['news'] as &$x){if((int)$x['id']===(int)$rm[1]){unset($x['imgUrl'],$x['imgCredit'],$x['imgLink'],$x['imgSource']);$x['imgTries']=0;if(!empty($rm[2])){$x['entity']=trim($rm[2]);unset($x['person']);}$found=true;}}unset($x);if(!$found)res($id,text('Haber yok',true));$r=skyturk_images($d['news'],5,30);save($d);foreach($d['news'] as $x)if((int)$x['id']===(int)$rm[1])res($id,text(['ok'=>true,'imgUrl'=>$x['imgUrl']??null,'imgCredit'=>$x['imgCredit']??null,'result'=>$r]));}
  if(preg_match('/^BUDGET_SET\s+(\d+)$/',trim($a['question']??''),$bs)){$bf=__DIR__.'/budget.json';file_put_contents($bf,json_encode([date('Y-m-d')=>(int)$bs[1]]));res($id,text(['ok'=>true,'today_used'=>(int)$bs[1]]));}
  if(preg_match('/^KISI_TARA\s+([a-z-]+)$/',trim($a['question']??''),$km)){require_once __DIR__.'/rewrite.php';require_once __DIR__.'/images.php';$d=load();$r1=skyturk_persons($d['news'],$km[1],40);$r2=skyturk_images($d['news'],40,60);save($d);logm('MCP kisi_tara '.json_encode([$r1,$r2]));res($id,text(['persons'=>$r1,'images'=>$r2]));}
  if(preg_match('/^BOOST\s+([a-z-]+)\s+(\d+)$/',trim($a['question']??''),$bm)){file_put_contents(__DIR__.'/boost.json',json_encode(['cat'=>$bm[1],'n'=>min(40,(int)$bm[2]),'t'=>time()]));logm('MCP boost '.$bm[1].' '.$bm[2]);res($id,text(['ok'=>true,'boost'=>$bm[1],'n'=>(int)$bm[2],'note'=>'fetch_rss ile tetikleyin']));}
  if(preg_match('/^FETCHTEST\s+(https?:\/\/\S+)(?:\s+(\d+))?$/',trim($a['question']??''),$fm)){$fl=(int)($fm[2]??600);$ch=curl_init($fm[1]);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>1,CURLOPT_FOLLOWLOCATION=>1,CURLOPT_TIMEOUT=>12,CURLOPT_HEADER=>1,CURLOPT_USERAGENT=>'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36',CURLOPT_HTTPHEADER=>['Accept: application/rss+xml, application/xml, text/xml;q=0.9, */*;q=0.8','Accept-Language: tr-TR,tr;q=0.9'],CURLOPT_ENCODING=>'']);$r=curl_exec($ch);$i=curl_getinfo($ch);$err=curl_error($ch);curl_close($ch);res($id,text(['code'=>$i['http_code'],'final'=>$i['url'],'type'=>$i['content_type'],'err'=>$err,'len'=>strlen((string)$r),'head'=>mb_substr((string)$r,0,$fl),'body'=>$fl>600?mb_substr((string)$r,(int)($i['header_size']??0),$fl):null]));}
  if(preg_match('/^SETSETTINGS\s+(\{.*\})$/s',trim($a['question']??''),$sm)){$j=json_decode($sm[1],true);if(!is_array($j))res($id,text('JSON hatalı',true));$d=load();foreach(['pages','ads','social','kvkk','smtp','theme'] as $dk){ if(isset($j[$dk])&&is_array($j[$dk])) $j[$dk]=array_merge($d['settings'][$dk]??[],$j[$dk]); }$d['settings']=array_merge($d['settings']??[],$j);save($d);logm('MCP settings '.implode(',',array_keys($j)));res($id,text(['ok'=>true,'settings'=>array_keys($j)]));}
  if(trim($a['question']??'')==='FIKSTUR_CEK'){require_once __DIR__.'/fixtures.php';$r=skyturk_fixtures();logm('MCP fikstur '.json_encode($r));res($id,text($r));}
  if(preg_match('/^GAZETE_SIL\s+(\d{4}-\d{2}-\d{2})$/',trim($a['question']??''),$dm)){$gd=dirname(__DIR__).'/gazete';$f=$gd.'/issues.json';$L=file_exists($f)?(json_decode(file_get_contents($f),true)?:[]):[];$L=array_values(array_filter($L,fn($i)=>($i['date']??'')!==$dm[1]));file_put_contents($f,json_encode($L,JSON_UNESCAPED_UNICODE));foreach(glob($gd.'/sayi-*-'.$dm[1].'.*') as $x)@unlink($x);logm('MCP gazete sil '.$dm[1]);res($id,text(['ok'=>true,'remaining'=>count($L)]));}
  if(preg_match('/^GAZETE_URET(?:\s+(\d{4}-\d{2}-\d{2}))?$/',trim($a['question']??''),$gm)){require_once __DIR__.'/gazete.php';$r=skyturk_gazete_build(true,$gm[1]??null);logm('MCP gazete(poll) '.json_encode($r,JSON_UNESCAPED_UNICODE));res($id,text($r));}
  if(preg_match('/^SETSECRET (ANTHROPIC_KEY|REWRITE_MODEL|PEXELS_KEY|BREVO_KEY|SMTP_PASS|IG_TOKEN|IG_APP_SECRET)=(.+)$/s',trim($a['question']??''),$mm)){$sec=file_exists(__DIR__.'/secrets.php')?(include __DIR__.'/secrets.php'):[];$sec[$mm[1]]=trim($mm[2]);file_put_contents(__DIR__.'/secrets.php',"<?php return ".var_export($sec,true).";\n",LOCK_EX);logm('MCP set_secret(poll) '.$mm[1]);res($id,text(['ok'=>true,'secret_set'=>$mm[1],'has_anthropic'=>!empty($sec['ANTHROPIC_KEY']),'has_pexels'=>!empty($sec['PEXELS_KEY'])]));}
  if(preg_match('/^PUSHFILE\s+(\S+)\s+([A-Za-z0-9+\/=\r\n]+)$/s',trim($a['question']??''),$pf)){$rel=ltrim(str_replace('\\','/',$pf[1]),'/');if(strpos($rel,'..')!==false||!preg_match('#^[A-Za-z0-9_./-]+$#',$rel))res($id,text('gecersiz yol',true));$prot=['api/data.json','api/secrets.php','api/config.php','api/ratelimit.json'];if(in_array($rel,$prot))res($id,text('korumali dosya',true));$root=dirname(__DIR__);$dest=$root.'/'.$rel;$bin=base64_decode(preg_replace('/\s+/','',$pf[2]),true);if($bin===false)res($id,text('base64 hatali',true));$dd=dirname($dest);if(!is_dir($dd))@mkdir($dd,0755,true);$ok=@file_put_contents($dest,$bin,LOCK_EX);if($ok===false)res($id,text('yazilamadi: '.$rel,true));@file_put_contents($root.'/api/.git_sha','pushfile '.date('Y-m-d H:i'));logm('MCP pushfile '.$rel.' ('.$ok.'b)');res($id,text(['ok'=>true,'file'=>$rel,'bytes'=>$ok,'sha1'=>sha1($bin)]));}
  $d=load();$q=['id'=>'p'.time(),'q'=>$a['question'],'o'=>array_map(fn($o)=>[$o,0],$a['options']),'votes'=>0,'open'=>true];array_unshift($d['polls'],$q);save($d);res($id,text(['ok'=>true,'poll'=>$q]));}
 case 'toggle_poll':{$d=load();$ok=false;foreach($d['polls'] as &$q)if($q['id']===$a['id']){$q['open']=(bool)$a['open'];$ok=true;}unset($q);if(!$ok)res($id,text('Anket bulunamadı',true));save($d);res($id,text(['ok'=>true]));}
 case 'deploy_from_github':{$ref=preg_replace('/[^a-zA-Z0-9_.\/-]/','',$a['ref']??'main');$url="https://codeload.github.com/erkankork-beep/skyturk/zip/refs/heads/$ref";
  $ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>1,CURLOPT_FOLLOWLOCATION=>1,CURLOPT_TIMEOUT=>60,CURLOPT_USERAGENT=>'SKYTURK-deploy']);$zipdata=curl_exec($ch);$code=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);
  if(!$zipdata||$code!=200)res($id,text("GitHub'dan indirilemedi (HTTP $code)",true));
  $tmp=sys_get_temp_dir().'/skyturk_'.uniqid();$zp=$tmp.'.zip';file_put_contents($zp,$zipdata);$z=new ZipArchive();if($z->open($zp)!==true)res($id,text('Zip açılamadı',true));mkdir($tmp);$z->extractTo($tmp);$z->close();@unlink($zp);
  $root=glob($tmp.'/*',GLOB_ONLYDIR)[0]??null;if(!$root)res($id,text('Paket boş',true));
  $dst=dirname(__DIR__);$files=['index.html','404.html','.htaccess','robots.txt','cms/.htaccess','cms/index.html','api/fetch.php','api/feeds.php','api/data.php','api/.htaccess','api/'.basename(__FILE__),'api/rewrite.php','api/images.php','api/videos.php','api/hit.php','api/status.php','api/auth.php','api/session.php','api/credit.php','api/gazete.php','api/fixtures.php','api/media.php','api/system.php','api/mailer.php','api/social.php','media/iremora-970x90.png','media/grand-signature-300x250.jpg','api/lib/tfpdf.php','api/lib/font/unifont/ttfonts.php','api/lib/font/unifont/DejaVuSans.ttf','api/lib/font/unifont/DejaVuSans-Bold.ttf','api/lib/font/unifont/DejaVuSansCondensed.ttf','api/lib/font/unifont/DejaVuSansCondensed-Bold.ttf','api/lib/font/unifont/DejaVuSerif-Bold.ttf'];$done=[];
  foreach($files as $f){if(file_exists("$root/$f")){@mkdir(dirname("$dst/$f"),0755,true);copy("$root/$f","$dst/$f");$done[]=$f;}}
  $sha=trim(@file_get_contents("$root/.git_sha")?:'');logm('MCP deploy '.$ref.' → '.count($done).' dosya');
  res($id,text(['ok'=>true,'ref'=>$ref,'files'=>$done,'not_in_repo'=>array_values(array_diff($files,$done))]));}
 case 'set_secret':{$sec=file_exists(__DIR__.'/secrets.php')?(include __DIR__.'/secrets.php'):[];$sec[$a['name']]=trim($a['value']);file_put_contents(__DIR__.'/secrets.php',"<?php return ".var_export($sec,true).";\n",LOCK_EX);logm('MCP set_secret '.$a['name']);res($id,text(['ok'=>true,'has_key'=>!empty($sec['ANTHROPIC_KEY']),'model'=>$sec['REWRITE_MODEL']??'claude-haiku-4-5-20251001']));}
 case 'rewrite_now':{require_once __DIR__.'/rewrite.php';$d=load();$r=skyturk_rewrite($d['news'],max(1,min(20,(int)($a['max']??20))),40);save($d);logm('MCP rewrite '.json_encode($r));res($id,text($r));}
 case 'images_now':{require_once __DIR__.'/images.php';$d=load();$r=skyturk_images($d['news'],max(1,min(30,(int)($a['max']??30))),40);save($d);logm('MCP images '.json_encode($r));res($id,text($r));}
 case 'gazete_now':{require_once __DIR__.'/gazete.php';$r=skyturk_gazete_build(!empty($a['force']));logm('MCP gazete '.json_encode($r,JSON_UNESCAPED_UNICODE));res($id,text($r));}
 case 'get_log':{res($id,text(['rss'=>explode("\n",substr((string)@file_get_contents(__DIR__.'/fetch.log'),0,2000)),'mcp'=>explode("\n",substr((string)@file_get_contents($LOG),0,2000))]));}
 default: err($id,-32602,'Unknown tool: '.$name);
}}catch(Throwable $e){res($id,text('Hata: '.$e->getMessage(),true));}
